# Generated by Django 4.0.6 on 2022-08-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['inline_customizable_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='inline_customizable_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
