# Generated by Django 4.0.6 on 2022-08-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['priority']},
        ),
    ]
