# Generated by Django 4.0.6 on 2022-08-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_image_inline_customizable_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='priority',
        ),
    ]
