# Generated by Django 4.0.6 on 2022-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='inline_customizable_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Приоритет при отображении'),
        ),
    ]
